server:
  port: "8080"
  host: "localhost"

websites:
  - name: "Self Employment"
    url: "https://philgear.biz"
    last_update: "2024-12-17"
    description: "My personal business website showcasing services and portfolio"
  - name: "Artistic Development Portfolio"
    url: "https://geararts.dev"
    last_update: "2024-12-13"
    description: "A collection of my artistic development projects and experiments"
  - name: "Photography Portfolio"
    url: "https://philgearphotography.com"
    last_update: "2024-12-18"
    description: "Showcasing my photography work and services"

social_media:
  - platform: "BlueSky"
    url: "https://bsky.app/profile/philgear.bsky.social"
    last_update: "2025-01-01"
    description: "Sharing thoughts and engaging with the BlueSky community"
  - platform: "500px"
    url: "https://500px.com/p/philgear"
    last_update: "2024-12-16"
    description: "Showcasing my best photography work"
  - platform: "LinkedIn"
    url: "https://linkedin.com/in/philgear"
    last_update: "2024-12-15"
    description: "Professional networking and career updates"
  - platform: "Behance"
    url: "https://www.behance.net/philgear"
    last_update: "2017-12-20"
    description: "Displaying my design projects and creative work"
  - platform: "GitHub"
    url: "https://github.com/philgear"
    last_update: "2024-12-18"
    description: "Open-source contributions and personal coding projects"
  - platform: "Instagram"
    url: "https://instagram.com/philgear"
    last_update: "2015-11-11"
    description: "Visual storytelling and daily life snapshots"

features:
  enable_dark_mode: true
  enable_analytics: false

page_content:
  title: "Phil Gear - Mentor | Action-Taker"
  tagline: "Mentor | Action-Taker"
  footer_text: "© 2024 Phil Gear. Dedicated to helping others and taking action."
